### ISSUE TITLE
Add SCP-1576 translations in the 12.0 update since theres a new SCP.

### ISSUE THREAD

**Issue by skyisbluelol** [CanThisNameNotBeStolenPlease/ModernEnglish_SCPSL#1]
![image](https://user-images.githubusercontent.com/120991444/209415159-4946c639-c714-4c27-a844-d54641aa8a9c.png)

Consider adding some translations like the other ones you have, with SCP-1576 because it is new and looks better then the default without any.

**Comment by CanThisNameNotBeStolenPlease** [comment]
Fixed (2022-12-25 ver)
